<?php

namespace Container3qKfEDg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContratService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.G6bTIky.App\Entity\Contrat' shared service.
     *
     * @return \App\Entity\Contrat
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.G6bTIky": it references class "App\\Entity\\Contrat" but no such service exists.');
    }
}
