<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGxziVW4\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGxziVW4/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerGxziVW4.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerGxziVW4\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerGxziVW4\App_KernelProdContainer([
    'container.build_hash' => 'GxziVW4',
    'container.build_id' => '3771b7d2',
    'container.build_time' => 1655714689,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGxziVW4');
