<?php

namespace ContainerUtKfrfr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_G6bTIkyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.G6bTIky' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.G6bTIky'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'contrat' => ['privates', '.errored..service_locator.G6bTIky.App\\Entity\\Contrat', NULL, 'Cannot autowire service ".service_locator.G6bTIky": it references class "App\\Entity\\Contrat" but no such service exists.'],
            'payement' => ['privates', '.errored..service_locator.G6bTIky.App\\Entity\\Payement', NULL, 'Cannot autowire service ".service_locator.G6bTIky": it references class "App\\Entity\\Payement" but no such service exists.'],
        ], [
            'contrat' => 'App\\Entity\\Contrat',
            'payement' => 'App\\Entity\\Payement',
        ]);
    }
}
