<?php

namespace Container5sxTxQG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HBK9LxUService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.hBK9LxU' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hBK9LxU'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\ContratController::createContrat' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\ContratController::deleteContrat' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\ContratController::displayContrats' => ['privates', '.service_locator.i0bGDgR', 'get_ServiceLocator_I0bGDgRService', true],
            'App\\Controller\\ContratController::updateContrat' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\IndexController::createClient' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\IndexController::deleteClient' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\IndexController::index' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\IndexController::sendEmail' => ['privates', '.service_locator.GyY0RxJ', 'get_ServiceLocator_GyY0RxJService', true],
            'App\\Controller\\IndexController::updateClient' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\PayementController::calculMontantRestant' => ['privates', '.service_locator.G6bTIky', 'get_ServiceLocator_G6bTIkyService', true],
            'App\\Controller\\PayementController::createPayement' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\PayementController::displayPayements' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\PayementController::majMontantRestant' => ['privates', '.service_locator.G6bTIky', 'get_ServiceLocator_G6bTIkyService', true],
            'App\\Controller\\PayementController::nouvelleBalanceApresPaiement' => ['privates', '.service_locator.G6bTIky', 'get_ServiceLocator_G6bTIkyService', true],
            'App\\Controller\\PayementController::nouvelleBalanceApresRemboursement' => ['privates', '.service_locator.G6bTIky', 'get_ServiceLocator_G6bTIkyService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'App\\Controller\\ContratController:createContrat' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\ContratController:deleteContrat' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\ContratController:displayContrats' => ['privates', '.service_locator.i0bGDgR', 'get_ServiceLocator_I0bGDgRService', true],
            'App\\Controller\\ContratController:updateContrat' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\IndexController:createClient' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\IndexController:deleteClient' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\IndexController:index' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\IndexController:sendEmail' => ['privates', '.service_locator.GyY0RxJ', 'get_ServiceLocator_GyY0RxJService', true],
            'App\\Controller\\IndexController:updateClient' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\PayementController:calculMontantRestant' => ['privates', '.service_locator.G6bTIky', 'get_ServiceLocator_G6bTIkyService', true],
            'App\\Controller\\PayementController:createPayement' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\PayementController:displayPayements' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\PayementController:majMontantRestant' => ['privates', '.service_locator.G6bTIky', 'get_ServiceLocator_G6bTIkyService', true],
            'App\\Controller\\PayementController:nouvelleBalanceApresPaiement' => ['privates', '.service_locator.G6bTIky', 'get_ServiceLocator_G6bTIkyService', true],
            'App\\Controller\\PayementController:nouvelleBalanceApresRemboursement' => ['privates', '.service_locator.G6bTIky', 'get_ServiceLocator_G6bTIkyService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
        ], [
            'App\\Controller\\ContratController::createContrat' => '?',
            'App\\Controller\\ContratController::deleteContrat' => '?',
            'App\\Controller\\ContratController::displayContrats' => '?',
            'App\\Controller\\ContratController::updateContrat' => '?',
            'App\\Controller\\IndexController::createClient' => '?',
            'App\\Controller\\IndexController::deleteClient' => '?',
            'App\\Controller\\IndexController::index' => '?',
            'App\\Controller\\IndexController::sendEmail' => '?',
            'App\\Controller\\IndexController::updateClient' => '?',
            'App\\Controller\\PayementController::calculMontantRestant' => '?',
            'App\\Controller\\PayementController::createPayement' => '?',
            'App\\Controller\\PayementController::displayPayements' => '?',
            'App\\Controller\\PayementController::majMontantRestant' => '?',
            'App\\Controller\\PayementController::nouvelleBalanceApresPaiement' => '?',
            'App\\Controller\\PayementController::nouvelleBalanceApresRemboursement' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\ContratController:createContrat' => '?',
            'App\\Controller\\ContratController:deleteContrat' => '?',
            'App\\Controller\\ContratController:displayContrats' => '?',
            'App\\Controller\\ContratController:updateContrat' => '?',
            'App\\Controller\\IndexController:createClient' => '?',
            'App\\Controller\\IndexController:deleteClient' => '?',
            'App\\Controller\\IndexController:index' => '?',
            'App\\Controller\\IndexController:sendEmail' => '?',
            'App\\Controller\\IndexController:updateClient' => '?',
            'App\\Controller\\PayementController:calculMontantRestant' => '?',
            'App\\Controller\\PayementController:createPayement' => '?',
            'App\\Controller\\PayementController:displayPayements' => '?',
            'App\\Controller\\PayementController:majMontantRestant' => '?',
            'App\\Controller\\PayementController:nouvelleBalanceApresPaiement' => '?',
            'App\\Controller\\PayementController:nouvelleBalanceApresRemboursement' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
