<?php

namespace Container5sxTxQG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPayementService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.G6bTIky.App\Entity\Payement' shared service.
     *
     * @return \App\Entity\Payement
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.G6bTIky": it references class "App\\Entity\\Payement" but no such service exists.');
    }
}
