<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5sxTxQG\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5sxTxQG/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/Container5sxTxQG.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\Container5sxTxQG\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \Container5sxTxQG\App_KernelTestDebugContainer([
    'container.build_hash' => '5sxTxQG',
    'container.build_id' => '2568ad75',
    'container.build_time' => 1654184303,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5sxTxQG');
