<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'contrat_create' => [[], ['_controller' => 'App\\Controller\\ContratController::createContrat'], [], [['text', '/contrat/create']], [], [], []],
    'contrat_delete' => [['contratId'], ['_controller' => 'App\\Controller\\ContratController::deleteContrat'], [], [['variable', '/', '[^/]++', 'contratId', true], ['text', '/contrat/delete']], [], [], []],
    'contrat_display' => [['clientId'], ['_controller' => 'App\\Controller\\ContratController::displayContrats'], [], [['variable', '/', '[^/]++', 'clientId', true], ['text', '/display/contrats']], [], [], []],
    'contrat_update' => [['contratId'], ['_controller' => 'App\\Controller\\ContratController::updateContrat'], [], [['variable', '/', '[^/]++', 'contratId', true], ['text', '/contrat/update']], [], [], []],
    'app_index' => [[], ['_controller' => 'App\\Controller\\IndexController::index'], [], [['text', '/']], [], [], []],
    'client_create' => [[], ['_controller' => 'App\\Controller\\IndexController::createClient'], [], [['text', '/client/create']], [], [], []],
    'client_delete' => [['clientId'], ['_controller' => 'App\\Controller\\IndexController::deleteClient'], [], [['variable', '/', '[^/]++', 'clientId', true], ['text', '/client/delete']], [], [], []],
    'client_update' => [['clientId'], ['_controller' => 'App\\Controller\\IndexController::updateClient'], [], [['variable', '/', '[^/]++', 'clientId', true], ['text', '/client/update']], [], [], []],
    'mail' => [[], ['_controller' => 'App\\Controller\\IndexController::sendEmail'], [], [['text', '/email']], [], [], []],
    'payements_display' => [['contratId'], ['_controller' => 'App\\Controller\\PayementController::displayPayements'], [], [['variable', '/', '[^/]++', 'contratId', true], ['text', '/display/payements']], [], [], []],
    'payement_create' => [['contratId'], ['_controller' => 'App\\Controller\\PayementController::createPayement'], [], [['variable', '/', '[^/]++', 'contratId', true], ['text', '/payement/create']], [], [], []],
];
