<?php

namespace ContainerGxziVW4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContratControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\ContratController' shared autowired service.
     *
     * @return \App\Controller\ContratController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\ContratController'] = $instance = new \App\Controller\ContratController();

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\ContratController', $container));

        return $instance;
    }
}
