<?php

namespace ContainerGxziVW4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPayementTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\PayementType' shared autowired service.
     *
     * @return \App\Form\PayementType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\PayementType'] = new \App\Form\PayementType();
    }
}
